## Generated by projecttemplates (https://jasenfinch.github.io/projecttemplates/) v0.5.0
## Execute this script to run the project analysis
targets::tar_make()

pipeline_graph <- targets::tar_visnetwork(label = c("time", "size"))
visNetwork::visSave(pipeline_graph,
                    file = "exports/pipeline_graph.html")