## Generated by projecttemplates (https://jasenfinch.github.io/projecttemplates/) v0.5.0

"R/targets/" %>%
  list.files(full.names = TRUE) %>%
  purrr::walk(source)  

list(
  KEGG_compound_targets,
  MF_selection_targets,
  spiked_urine_targets,
  brachy_targets,
  assignment_results_targets,
  benchmarking_targets,
  manuscript_targets
)
