name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  # Run tests for any PRs.
  pull_request:
       
jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-22.04
       
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file misc/docker/Dockerfile --tag molecular-formula-assignment
       
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
       
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/ghcr.io/${{ github.actor }}/molecular-formula-assignment
          docker tag molecular-formula-assignment $IMAGE_ID:latest
          docker push $IMAGE_ID:latest